/* 
 * <auto-generated>
 * Connect API
 *
 * Mbed Cloud Connect API allows web applications to communicate with devices. You can subscribe to device resources and read/write values to them. mbed Cloud Connect makes connectivity to devices easy by queuing requests and caching resource values.
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * </auto-generated>
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mds.Api;
using mds.Model;
using mds.Client;
using System.Reflection;

namespace mds.Test
{
    /// <summary>
    ///  Class for testing NotificationData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificationDataTests
    {
        // TODO uncomment below to declare an instance variable for NotificationData
        //private NotificationData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotificationData
            //instance = new NotificationData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificationData
        /// </summary>
        [Test]
        public void NotificationDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NotificationData
            //Assert.IsInstanceOfType<NotificationData> (instance, "variable 'instance' is a NotificationData");
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'MaxAge'
        /// </summary>
        [Test]
        public void MaxAgeTest()
        {
            // TODO unit test for the property 'MaxAge'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Test]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'Ep'
        /// </summary>
        [Test]
        public void EpTest()
        {
            // TODO unit test for the property 'Ep'
        }
        /// <summary>
        /// Test the property 'Ct'
        /// </summary>
        [Test]
        public void CtTest()
        {
            // TODO unit test for the property 'Ct'
        }

    }

}
