// <auto-generated>
//
// Generated by
//                     _                        _
//   /\/\   __ _ _ __ | |__   __ _ ___ ___  ___| |_
//  /    \ / _` | '_ \| '_ \ / _` / __/ __|/ _ \ __|
// / /\/\ \ (_| | | | | | | | (_| \__ \__ \  __/ |_
// \/    \/\__,_|_| |_|_| |_|\__,_|___/___/\___|\__| v 1.0.0
//
// <copyright file="VerificationResponse.cs" company="Arm">
// Copyright (c) Arm. All rights reserved.
// </copyright>
// </auto-generated>

namespace MbedCloud.SDK.Entities
{
    using MbedCloud.SDK.Common;

    /// <summary>
    /// VerificationResponse
    /// </summary>
    public class VerificationResponse : Entity
    {
        /// <summary>
        /// message
        /// </summary>
        public string Message
        {
            get;
            set;
        }

        /// <summary>
        /// successful
        /// </summary>
        public bool? Successful
        {
            get;
            set;
        }
    }
}