// <auto-generated>
//
// Generated by
//                     _                        _
//   /\/\   __ _ _ __ | |__   __ _ ___ ___  ___| |_
//  /    \ / _` | '_ \| '_ \ / _` / __/ __|/ _ \ __|
// / /\/\ \ (_| | | | | | | | (_| \__ \__ \  __/ |_
// \/    \/\__,_|_| |_|_| |_|\__,_|___/___/\___|\__| v 2.0.0
//
// <copyright file="DeviceEnrollmentBulkDelete.cs" company="Arm">
// Copyright (c) Arm. All rights reserved.
// </copyright>
// </auto-generated>

namespace Mbed.Cloud.Foundation
{
    using Mbed.Cloud.Common;
    using System;
    using Mbed.Cloud.Foundation.Enums;

    /// <summary>
    /// DeviceEnrollmentBulkDelete
    /// </summary>
    public class DeviceEnrollmentBulkDelete : Entity, IDeviceEnrollmentBulkDelete
    {
        /// <summary>
        /// account_id
        /// </summary>
        public string AccountId
        {
            get;
            internal set;
        }

        /// <summary>
        /// completed_at
        /// </summary>
        public DateTime? CompletedAt
        {
            get;
            internal set;
        }

        /// <summary>
        /// created_at
        /// </summary>
        public DateTime? CreatedAt
        {
            get;
            internal set;
        }

        /// <summary>
        /// errors_count
        /// </summary>
        public int? ErrorsCount
        {
            get;
            internal set;
        }

        /// <summary>
        /// errors_report_file
        /// </summary>
        public string ErrorsReportFile
        {
            get;
            internal set;
        }

        /// <summary>
        /// full_report_file
        /// </summary>
        public string FullReportFile
        {
            get;
            internal set;
        }

        /// <summary>
        /// processed_count
        /// </summary>
        public int? ProcessedCount
        {
            get;
            internal set;
        }

        /// <summary>
        /// status
        /// </summary>
        public DeviceEnrollmentBulkDeleteStatus? Status
        {
            get;
            internal set;
        }

        /// <summary>
        /// total_count
        /// </summary>
        public int? TotalCount
        {
            get;
            internal set;
        }
    }
}