// <auto-generated>
//
// Generated by
//                     _                        _
//   /\/\   __ _ _ __ | |__   __ _ ___ ___  ___| |_
//  /    \ / _` | '_ \| '_ \ / _` / __/ __|/ _ \ __|
// / /\/\ \ (_| | | | | | | | (_| \__ \__ \  __/ |_
// \/    \/\__,_|_| |_|_| |_|\__,_|___/___/\___|\__| v 2.0.0
//
// <copyright file="FirmwareManifest.cs" company="Arm">
// Copyright (c) Arm. All rights reserved.
// </copyright>
// </auto-generated>

namespace Mbed.Cloud.Foundation
{
    using Mbed.Cloud.Common;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// FirmwareManifest
    /// </summary>
    public class FirmwareManifest : Entity, IFirmwareManifest
    {
        internal static Dictionary<string, string> Renames = new Dictionary<string, string>() { { "DatafileUrl", "datafile" }, { "KeyTableUrl", "key_table" }, };

        [JsonConverter(typeof(CustomDateConverter), "yyyy-MM-dd'T'HH:mm:ss.fffZ")]
        /// <summary>
        /// created_at
        /// </summary>
        public DateTime? CreatedAt
        {
            get;
            internal set;
        }

        /// <summary>
        /// datafile_size
        /// </summary>
        public long? DatafileSize
        {
            get;
            internal set;
        }

        /// <summary>
        /// datafile_url
        /// </summary>
        public string DatafileUrl
        {
            get;
            internal set;
        }

        /// <summary>
        /// description
        /// </summary>
        public string Description
        {
            get;
            set;
        }

        /// <summary>
        /// device_class
        /// </summary>
        public string DeviceClass
        {
            get;
            internal set;
        }

        /// <summary>
        /// key_table_url
        /// </summary>
        public string KeyTableUrl
        {
            get;
            internal set;
        }

        /// <summary>
        /// name
        /// </summary>
        public string Name
        {
            get;
            set;
        }
        [JsonConverter(typeof(CustomDateConverter), "yyyy-MM-dd'T'HH:mm:ss.fffZ")]
        /// <summary>
        /// timestamp
        /// </summary>
        public DateTime? Timestamp
        {
            get;
            internal set;
        }
        [JsonConverter(typeof(CustomDateConverter), "yyyy-MM-dd'T'HH:mm:ss.fffZ")]
        /// <summary>
        /// updated_at
        /// </summary>
        public DateTime? UpdatedAt
        {
            get;
            internal set;
        }
    }
}