// <auto-generated>
//
// Generated by
//                     _                        _
//   /\/\   __ _ _ __ | |__   __ _ ___ ___  ___| |_
//  /    \ / _` | '_ \| '_ \ / _` / __/ __|/ _ \ __|
// / /\/\ \ (_| | | | | | | | (_| \__ \__ \  __/ |_
// \/    \/\__,_|_| |_|_| |_|\__,_|___/___/\___|\__| v 2.0.0
//
// <copyright file="IApiKeyRepository.cs" company="Arm">
// Copyright (c) Arm. All rights reserved.
// </copyright>
// </auto-generated>

namespace Mbed.Cloud.Foundation.Entities
{
    using Mbed.Cloud.Foundation.Common;
    using Mbed.Cloud.Foundation.ListOptions;
    using System.Threading.Tasks;
    using MbedCloudSDK.Exceptions;
    using System.Collections.Generic;
    using System;
    using Mbed.Cloud.Foundation.RestClient;

    /// <summary>
    /// ApiKeyRepository
    /// </summary>
    public interface IApiKeyRepository
    {
        Task<ApiKey> Create(ApiKey request);
        Task Delete(string id);
        Task<ApiKey> Get(string id);
        PaginatedResponse<IApiKeyListOptions, ApiKey> List(IApiKeyListOptions options = null);
        Task<ApiKey> Me();
        Task<ApiKey> Update(string id, ApiKey request);
    }
}