/* 
 * <auto-generated>
 * Bootstrap API
 *
 * Mbed Cloud Bootstrap API allows web applications to control the device bootstrapping process.
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * </auto-generated>
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = connector_bootstrap.Client.SwaggerDateConverter;

namespace connector_bootstrap.Model
{
    /// <summary>
    /// PreSharedKeyWithoutSecret
    /// </summary>
    [DataContract]
    public partial class PreSharedKeyWithoutSecret :  IEquatable<PreSharedKeyWithoutSecret>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreSharedKeyWithoutSecret" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PreSharedKeyWithoutSecret() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PreSharedKeyWithoutSecret" /> class.
        /// </summary>
        /// <param name="CreatedAt">The date-time (RFC3339) when this pre-shared key was uploaded to Mbed Cloud..</param>
        /// <param name="EndpointName">The unique endpoint identifier that this pre-shared key applies to. 16-64 [printable](https://en.wikipedia.org/wiki/ASCII#Printable_characters) (non-control) ASCII characters. (required).</param>
        public PreSharedKeyWithoutSecret(DateTime? CreatedAt = default(DateTime?), string EndpointName = default(string))
        {
            // to ensure "EndpointName" is required (not null)
            if (EndpointName == null)
            {
                throw new InvalidDataException("EndpointName is a required property for PreSharedKeyWithoutSecret and cannot be null");
            }
            else
            {
                this.EndpointName = EndpointName;
            }
            this.CreatedAt = CreatedAt;
        }
        
        /// <summary>
        /// The date-time (RFC3339) when this pre-shared key was uploaded to Mbed Cloud.
        /// </summary>
        /// <value>The date-time (RFC3339) when this pre-shared key was uploaded to Mbed Cloud.</value>
        [DataMember(Name="created_at", EmitDefaultValue=false)]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The unique endpoint identifier that this pre-shared key applies to. 16-64 [printable](https://en.wikipedia.org/wiki/ASCII#Printable_characters) (non-control) ASCII characters.
        /// </summary>
        /// <value>The unique endpoint identifier that this pre-shared key applies to. 16-64 [printable](https://en.wikipedia.org/wiki/ASCII#Printable_characters) (non-control) ASCII characters.</value>
        [DataMember(Name="endpoint_name", EmitDefaultValue=false)]
        public string EndpointName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PreSharedKeyWithoutSecret {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  EndpointName: ").Append(EndpointName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PreSharedKeyWithoutSecret);
        }

        /// <summary>
        /// Returns true if PreSharedKeyWithoutSecret instances are equal
        /// </summary>
        /// <param name="input">Instance of PreSharedKeyWithoutSecret to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PreSharedKeyWithoutSecret input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.EndpointName == input.EndpointName ||
                    (this.EndpointName != null &&
                    this.EndpointName.Equals(input.EndpointName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                if (this.EndpointName != null)
                    hashCode = hashCode * 59 + this.EndpointName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EndpointName (string) pattern
            Regex regexEndpointName = new Regex(@"^[ -~]{16,64}$", RegexOptions.CultureInvariant);
            if (false == regexEndpointName.Match(this.EndpointName).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EndpointName, must match a pattern of " + regexEndpointName, new [] { "EndpointName" });
            }

            yield break;
        }
    }

}
