/* 
 * Update Service API
 *
 * This is the API Documentation for the mbed deployment service which is part of the update service.
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace update_service.Model
{
    /// <summary>
    /// ManifestContents
    /// </summary>
    [DataContract]
    public partial class ManifestContents :  IEquatable<ManifestContents>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManifestContents" /> class.
        /// </summary>
        /// <param name="Nonce">A 128-bit random field.</param>
        /// <param name="PayloadInfo">PayloadInfo.</param>
        /// <param name="ManifestVersion">The version of the manifest format being used..</param>
        /// <param name="DigestAlgorithm">DigestAlgorithm.</param>
        /// <param name="Text">Text.</param>
        /// <param name="Directives">Directives.</param>
        /// <param name="Timestamp">The time the manifest was created. The timestamp is stored as Unix time..</param>
        /// <param name="Dependenices">Dependenices.</param>
        /// <param name="Conditions">Conditions.</param>
        /// <param name="Aliases">Aliases.</param>
        public ManifestContents(string Nonce = default(string), ManifestContentsPayloadInfo PayloadInfo = default(ManifestContentsPayloadInfo), string ManifestVersion = default(string), ManifestContentsDigestAlgorithm DigestAlgorithm = default(ManifestContentsDigestAlgorithm), List<ManifestContentsText> Text = default(List<ManifestContentsText>), List<ManifestContentsDirectives> Directives = default(List<ManifestContentsDirectives>), int? Timestamp = default(int?), List<ManifestContentsPayloadInfoPayloadReference> Dependenices = default(List<ManifestContentsPayloadInfoPayloadReference>), List<ManifestContentsConditions> Conditions = default(List<ManifestContentsConditions>), List<ManifestContentsPayloadInfoPayloadReference> Aliases = default(List<ManifestContentsPayloadInfoPayloadReference>))
        {
            this.Nonce = Nonce;
            this.PayloadInfo = PayloadInfo;
            this.ManifestVersion = ManifestVersion;
            this.DigestAlgorithm = DigestAlgorithm;
            this.Text = Text;
            this.Directives = Directives;
            this.Timestamp = Timestamp;
            this.Dependenices = Dependenices;
            this.Conditions = Conditions;
            this.Aliases = Aliases;
        }
        
        /// <summary>
        /// A 128-bit random field
        /// </summary>
        /// <value>A 128-bit random field</value>
        [DataMember(Name="nonce", EmitDefaultValue=false)]
        public string Nonce { get; set; }
        /// <summary>
        /// Gets or Sets PayloadInfo
        /// </summary>
        [DataMember(Name="payloadInfo", EmitDefaultValue=false)]
        public ManifestContentsPayloadInfo PayloadInfo { get; set; }
        /// <summary>
        /// The version of the manifest format being used.
        /// </summary>
        /// <value>The version of the manifest format being used.</value>
        [DataMember(Name="manifestVersion", EmitDefaultValue=false)]
        public string ManifestVersion { get; set; }
        /// <summary>
        /// Gets or Sets DigestAlgorithm
        /// </summary>
        [DataMember(Name="digestAlgorithm", EmitDefaultValue=false)]
        public ManifestContentsDigestAlgorithm DigestAlgorithm { get; set; }
        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public List<ManifestContentsText> Text { get; set; }
        /// <summary>
        /// Gets or Sets Directives
        /// </summary>
        [DataMember(Name="directives", EmitDefaultValue=false)]
        public List<ManifestContentsDirectives> Directives { get; set; }
        /// <summary>
        /// The time the manifest was created. The timestamp is stored as Unix time.
        /// </summary>
        /// <value>The time the manifest was created. The timestamp is stored as Unix time.</value>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public int? Timestamp { get; set; }
        /// <summary>
        /// Gets or Sets Dependenices
        /// </summary>
        [DataMember(Name="dependenices", EmitDefaultValue=false)]
        public List<ManifestContentsPayloadInfoPayloadReference> Dependenices { get; set; }
        /// <summary>
        /// Gets or Sets Conditions
        /// </summary>
        [DataMember(Name="conditions", EmitDefaultValue=false)]
        public List<ManifestContentsConditions> Conditions { get; set; }
        /// <summary>
        /// Gets or Sets Aliases
        /// </summary>
        [DataMember(Name="aliases", EmitDefaultValue=false)]
        public List<ManifestContentsPayloadInfoPayloadReference> Aliases { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ManifestContents {\n");
            sb.Append("  Nonce: ").Append(Nonce).Append("\n");
            sb.Append("  PayloadInfo: ").Append(PayloadInfo).Append("\n");
            sb.Append("  ManifestVersion: ").Append(ManifestVersion).Append("\n");
            sb.Append("  DigestAlgorithm: ").Append(DigestAlgorithm).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Directives: ").Append(Directives).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Dependenices: ").Append(Dependenices).Append("\n");
            sb.Append("  Conditions: ").Append(Conditions).Append("\n");
            sb.Append("  Aliases: ").Append(Aliases).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ManifestContents);
        }

        /// <summary>
        /// Returns true if ManifestContents instances are equal
        /// </summary>
        /// <param name="other">Instance of ManifestContents to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ManifestContents other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Nonce == other.Nonce ||
                    this.Nonce != null &&
                    this.Nonce.Equals(other.Nonce)
                ) && 
                (
                    this.PayloadInfo == other.PayloadInfo ||
                    this.PayloadInfo != null &&
                    this.PayloadInfo.Equals(other.PayloadInfo)
                ) && 
                (
                    this.ManifestVersion == other.ManifestVersion ||
                    this.ManifestVersion != null &&
                    this.ManifestVersion.Equals(other.ManifestVersion)
                ) && 
                (
                    this.DigestAlgorithm == other.DigestAlgorithm ||
                    this.DigestAlgorithm != null &&
                    this.DigestAlgorithm.Equals(other.DigestAlgorithm)
                ) && 
                (
                    this.Text == other.Text ||
                    this.Text != null &&
                    this.Text.SequenceEqual(other.Text)
                ) && 
                (
                    this.Directives == other.Directives ||
                    this.Directives != null &&
                    this.Directives.SequenceEqual(other.Directives)
                ) && 
                (
                    this.Timestamp == other.Timestamp ||
                    this.Timestamp != null &&
                    this.Timestamp.Equals(other.Timestamp)
                ) && 
                (
                    this.Dependenices == other.Dependenices ||
                    this.Dependenices != null &&
                    this.Dependenices.SequenceEqual(other.Dependenices)
                ) && 
                (
                    this.Conditions == other.Conditions ||
                    this.Conditions != null &&
                    this.Conditions.SequenceEqual(other.Conditions)
                ) && 
                (
                    this.Aliases == other.Aliases ||
                    this.Aliases != null &&
                    this.Aliases.SequenceEqual(other.Aliases)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Nonce != null)
                    hash = hash * 59 + this.Nonce.GetHashCode();
                if (this.PayloadInfo != null)
                    hash = hash * 59 + this.PayloadInfo.GetHashCode();
                if (this.ManifestVersion != null)
                    hash = hash * 59 + this.ManifestVersion.GetHashCode();
                if (this.DigestAlgorithm != null)
                    hash = hash * 59 + this.DigestAlgorithm.GetHashCode();
                if (this.Text != null)
                    hash = hash * 59 + this.Text.GetHashCode();
                if (this.Directives != null)
                    hash = hash * 59 + this.Directives.GetHashCode();
                if (this.Timestamp != null)
                    hash = hash * 59 + this.Timestamp.GetHashCode();
                if (this.Dependenices != null)
                    hash = hash * 59 + this.Dependenices.GetHashCode();
                if (this.Conditions != null)
                    hash = hash * 59 + this.Conditions.GetHashCode();
                if (this.Aliases != null)
                    hash = hash * 59 + this.Aliases.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
