// <auto-generated>
//
// Generated by
//                     _                        _
//   /\/\   __ _ _ __ | |__   __ _ ___ ___  ___| |_
//  /    \ / _` | '_ \| '_ \ / _` / __/ __|/ _ \ __|
// / /\/\ \ (_| | | | | | | | (_| \__ \__ \  __/ |_
// \/    \/\__,_|_| |_|_| |_|\__,_|___/___/\___|\__| v 2.0.0
//
// <copyright file="SubtenantPolicyGroupRepository.cs" company="Arm">
// Copyright (c) Arm. All rights reserved.
// </copyright>
// </auto-generated>

namespace Mbed.Cloud.Foundation
{
    using Mbed.Cloud.Common;
    using Mbed.Cloud.Foundation;
    using System.Threading.Tasks;
    using MbedCloudSDK.Exceptions;
    using System.Collections.Generic;
    using System;
    using Mbed.Cloud.RestClient;

    /// <summary>
    /// SubtenantPolicyGroupRepository
    /// </summary>
    public class SubtenantPolicyGroupRepository : Repository, ISubtenantPolicyGroupRepository
    {
        public SubtenantPolicyGroupRepository()
        {
        }

        public SubtenantPolicyGroupRepository(Config config, Client client = null) : base(config, client)
        {
        }

        public PaginatedResponse<ISubtenantPolicyGroupSubtenantApiKeyListOptions, SubtenantApiKey> ApiKeys(string accountId, string id, ISubtenantPolicyGroupSubtenantApiKeyListOptions options = null)
        {
            try
            {
                var pathParams = new Dictionary<string, object> { { "account_id", accountId }, { "group_id", id }, };
                if (options == null)
                {
                    options = new SubtenantPolicyGroupSubtenantApiKeyListOptions();
                }

                Func<ISubtenantPolicyGroupSubtenantApiKeyListOptions, Task<ResponsePage<SubtenantApiKey>>> paginatedFunc = async (ISubtenantPolicyGroupSubtenantApiKeyListOptions _options) => { var queryParams = new Dictionary<string, object> { { "after", _options.After }, { "include", _options.Include }, { "limit", _options.Limit }, { "order", _options.Order }, }; return await Client.CallApi<ResponsePage<SubtenantApiKey>>(path: "/v3/accounts/{account_id}/policy-groups/{group_id}/api-keys", pathParams: pathParams, queryParams: queryParams, method: HttpMethods.GET); };
                return new PaginatedResponse<ISubtenantPolicyGroupSubtenantApiKeyListOptions, SubtenantApiKey>(paginatedFunc, options);
            }
            catch (ApiException e)
            {
                throw new CloudApiException(e.ErrorCode, e.Message, e.ErrorContent);
            }
        }

        public PaginatedResponse<ISubtenantPolicyGroupListOptions, SubtenantPolicyGroup> List(string accountId, ISubtenantPolicyGroupListOptions options = null)
        {
            try
            {
                var pathParams = new Dictionary<string, object> { { "account_id", accountId }, };
                if (options == null)
                {
                    options = new SubtenantPolicyGroupListOptions();
                }

                Func<ISubtenantPolicyGroupListOptions, Task<ResponsePage<SubtenantPolicyGroup>>> paginatedFunc = async (ISubtenantPolicyGroupListOptions _options) => { var queryParams = new Dictionary<string, object> { { "after", _options.After }, { "include", _options.Include }, { "limit", _options.Limit }, { "order", _options.Order }, { "name__eq", _options.Filter.GetEncodedValue("name", "$eq") }, }; return await Client.CallApi<ResponsePage<SubtenantPolicyGroup>>(path: "/v3/accounts/{account_id}/policy-groups", pathParams: pathParams, queryParams: queryParams, method: HttpMethods.GET); };
                return new PaginatedResponse<ISubtenantPolicyGroupListOptions, SubtenantPolicyGroup>(paginatedFunc, options);
            }
            catch (ApiException e)
            {
                throw new CloudApiException(e.ErrorCode, e.Message, e.ErrorContent);
            }
        }

        public async Task<SubtenantPolicyGroup> Read(string accountId, string id)
        {
            try
            {
                var pathParams = new Dictionary<string, object> { { "account_id", accountId }, { "group_id", id }, };
                return await Client.CallApi<SubtenantPolicyGroup>(path: "/v3/accounts/{account_id}/policy-groups/{group_id}", pathParams: pathParams, method: HttpMethods.GET);
            }
            catch (ApiException e)
            {
                throw new CloudApiException(e.ErrorCode, e.Message, e.ErrorContent);
            }
        }

        public PaginatedResponse<ISubtenantPolicyGroupSubtenantUserListOptions, SubtenantUser> Users(string accountId, string id, ISubtenantPolicyGroupSubtenantUserListOptions options = null)
        {
            try
            {
                var pathParams = new Dictionary<string, object> { { "account_id", accountId }, { "group_id", id }, };
                if (options == null)
                {
                    options = new SubtenantPolicyGroupSubtenantUserListOptions();
                }

                Func<ISubtenantPolicyGroupSubtenantUserListOptions, Task<ResponsePage<SubtenantUser>>> paginatedFunc = async (ISubtenantPolicyGroupSubtenantUserListOptions _options) => { var queryParams = new Dictionary<string, object> { { "after", _options.After }, { "include", _options.Include }, { "limit", _options.Limit }, { "order", _options.Order }, { "status__eq", _options.Filter.GetEncodedValue("status", "$eq") }, { "status__in", _options.Filter.GetEncodedValue("status", "$in") }, { "status__nin", _options.Filter.GetEncodedValue("status", "$nin") }, }; return await Client.CallApi<ResponsePage<SubtenantUser>>(path: "/v3/accounts/{account_id}/policy-groups/{group_id}/users", pathParams: pathParams, queryParams: queryParams, method: HttpMethods.GET); };
                return new PaginatedResponse<ISubtenantPolicyGroupSubtenantUserListOptions, SubtenantUser>(paginatedFunc, options);
            }
            catch (ApiException e)
            {
                throw new CloudApiException(e.ErrorCode, e.Message, e.ErrorContent);
            }
        }
    }
}