/* 
 * <auto-generated>
 * Connect CA API
 *
 * Connect CA API provides methods to create and get Developer certificate. Also Connect CA provides server-credentials for Bootstarp and LWM2M Server.
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * </auto-generated>
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connector_ca.Api;
using connector_ca.Model;
using connector_ca.Client;
using System.Reflection;

namespace connector_ca.Test
{
    /// <summary>
    ///  Class for testing DeveloperCertificateRequestData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeveloperCertificateRequestDataTests
    {
        // TODO uncomment below to declare an instance variable for DeveloperCertificateRequestData
        //private DeveloperCertificateRequestData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeveloperCertificateRequestData
            //instance = new DeveloperCertificateRequestData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeveloperCertificateRequestData
        /// </summary>
        [Test]
        public void DeveloperCertificateRequestDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeveloperCertificateRequestData
            //Assert.IsInstanceOfType<DeveloperCertificateRequestData> (instance, "variable 'instance' is a DeveloperCertificateRequestData");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
