// <auto-generated>
//
// Generated by
//                     _                        _
//   /\/\   __ _ _ __ | |__   __ _ ___ ___  ___| |_
//  /    \ / _` | '_ \| '_ \ / _` / __/ __|/ _ \ __|
// / /\/\ \ (_| | | | | | | | (_| \__ \__ \  __/ |_
// \/    \/\__,_|_| |_|_| |_|\__,_|___/___/\___|\__| v 2.0.0
//
// <copyright file="IDeviceDeviceListOptions.cs" company="Arm">
// Copyright (c) Arm. All rights reserved.
// </copyright>
// </auto-generated>

namespace Mbed.Cloud.Foundation
{
    using Mbed.Cloud.Common;
    using Mbed.Cloud.Common.Filters;
    using System.Collections.Generic;
    using System;
    using Mbed.Cloud.Foundation.Enums;

    /// <summary>
    /// DeviceDeviceListOptions
    /// </summary>
    public interface IDeviceDeviceListOptions : IQueryOptions
    {
        /// <summary>
        /// Filter object
        /// </summary>
        Filter Filter
        {
            get;
            set;
        }

        DeviceDeviceListOptions AccountIdEqualTo(string value);
        DeviceDeviceListOptions AccountIdNotEqualTo(string value);
        DeviceDeviceListOptions AccountIdIn(params string[] value);
        DeviceDeviceListOptions AccountIdNotIn(params string[] value);
        DeviceDeviceListOptions AutoUpdateEqualTo(bool value);
        DeviceDeviceListOptions AutoUpdateNotEqualTo(bool value);
        DeviceDeviceListOptions BootstrapExpirationDateIn(params DateTime[] value);
        DeviceDeviceListOptions BootstrapExpirationDateNotIn(params DateTime[] value);
        DeviceDeviceListOptions BootstrapExpirationDateLessThan(DateTime value);
        DeviceDeviceListOptions BootstrapExpirationDateGreaterThan(DateTime value);
        DeviceDeviceListOptions BootstrappedTimestampIn(params DateTime[] value);
        DeviceDeviceListOptions BootstrappedTimestampNotIn(params DateTime[] value);
        DeviceDeviceListOptions BootstrappedTimestampLessThan(DateTime value);
        DeviceDeviceListOptions BootstrappedTimestampGreaterThan(DateTime value);
        DeviceDeviceListOptions CaIdEqualTo(string value);
        DeviceDeviceListOptions CaIdNotEqualTo(string value);
        DeviceDeviceListOptions CaIdIn(params string[] value);
        DeviceDeviceListOptions CaIdNotIn(params string[] value);
        DeviceDeviceListOptions ConnectorExpirationDateIn(params DateTime[] value);
        DeviceDeviceListOptions ConnectorExpirationDateNotIn(params DateTime[] value);
        DeviceDeviceListOptions ConnectorExpirationDateLessThan(DateTime value);
        DeviceDeviceListOptions ConnectorExpirationDateGreaterThan(DateTime value);
        DeviceDeviceListOptions CreatedAtIn(params DateTime[] value);
        DeviceDeviceListOptions CreatedAtNotIn(params DateTime[] value);
        DeviceDeviceListOptions CreatedAtLessThan(DateTime value);
        DeviceDeviceListOptions CreatedAtGreaterThan(DateTime value);
        DeviceDeviceListOptions DeployedStateEqualTo(DeviceDeployedState value);
        DeviceDeviceListOptions DeployedStateNotEqualTo(DeviceDeployedState value);
        DeviceDeviceListOptions DeployedStateIn(params DeviceDeployedState[] value);
        DeviceDeviceListOptions DeployedStateNotIn(params DeviceDeployedState[] value);
        DeviceDeviceListOptions DeploymentEqualTo(string value);
        DeviceDeviceListOptions DeploymentNotEqualTo(string value);
        DeviceDeviceListOptions DeploymentIn(params string[] value);
        DeviceDeviceListOptions DeploymentNotIn(params string[] value);
        DeviceDeviceListOptions DescriptionEqualTo(string value);
        DeviceDeviceListOptions DescriptionNotEqualTo(string value);
        DeviceDeviceListOptions DescriptionIn(params string[] value);
        DeviceDeviceListOptions DescriptionNotIn(params string[] value);
        DeviceDeviceListOptions DeviceClassEqualTo(string value);
        DeviceDeviceListOptions DeviceClassNotEqualTo(string value);
        DeviceDeviceListOptions DeviceClassIn(params string[] value);
        DeviceDeviceListOptions DeviceClassNotIn(params string[] value);
        DeviceDeviceListOptions DeviceExecutionModeEqualTo(int value);
        DeviceDeviceListOptions DeviceExecutionModeNotEqualTo(int value);
        DeviceDeviceListOptions DeviceExecutionModeIn(params int[] value);
        DeviceDeviceListOptions DeviceExecutionModeNotIn(params int[] value);
        DeviceDeviceListOptions DeviceKeyEqualTo(string value);
        DeviceDeviceListOptions DeviceKeyNotEqualTo(string value);
        DeviceDeviceListOptions DeviceKeyIn(params string[] value);
        DeviceDeviceListOptions DeviceKeyNotIn(params string[] value);
        DeviceDeviceListOptions EndpointNameEqualTo(string value);
        DeviceDeviceListOptions EndpointNameNotEqualTo(string value);
        DeviceDeviceListOptions EndpointNameIn(params string[] value);
        DeviceDeviceListOptions EndpointNameNotIn(params string[] value);
        DeviceDeviceListOptions EndpointTypeEqualTo(string value);
        DeviceDeviceListOptions EndpointTypeNotEqualTo(string value);
        DeviceDeviceListOptions EndpointTypeIn(params string[] value);
        DeviceDeviceListOptions EndpointTypeNotIn(params string[] value);
        DeviceDeviceListOptions EnrolmentListTimestampIn(params DateTime[] value);
        DeviceDeviceListOptions EnrolmentListTimestampNotIn(params DateTime[] value);
        DeviceDeviceListOptions EnrolmentListTimestampLessThan(DateTime value);
        DeviceDeviceListOptions EnrolmentListTimestampGreaterThan(DateTime value);
        DeviceDeviceListOptions FirmwareChecksumEqualTo(string value);
        DeviceDeviceListOptions FirmwareChecksumNotEqualTo(string value);
        DeviceDeviceListOptions FirmwareChecksumIn(params string[] value);
        DeviceDeviceListOptions FirmwareChecksumNotIn(params string[] value);
        DeviceDeviceListOptions HostGatewayEqualTo(string value);
        DeviceDeviceListOptions HostGatewayNotEqualTo(string value);
        DeviceDeviceListOptions HostGatewayIn(params string[] value);
        DeviceDeviceListOptions HostGatewayNotIn(params string[] value);
        DeviceDeviceListOptions IdEqualTo(string value);
        DeviceDeviceListOptions IdNotEqualTo(string value);
        DeviceDeviceListOptions IdIn(params string[] value);
        DeviceDeviceListOptions IdNotIn(params string[] value);
        DeviceDeviceListOptions ManifestEqualTo(string value);
        DeviceDeviceListOptions ManifestNotEqualTo(string value);
        DeviceDeviceListOptions ManifestIn(params string[] value);
        DeviceDeviceListOptions ManifestNotIn(params string[] value);
        DeviceDeviceListOptions ManifestTimestampIn(params DateTime[] value);
        DeviceDeviceListOptions ManifestTimestampNotIn(params DateTime[] value);
        DeviceDeviceListOptions ManifestTimestampLessThan(DateTime value);
        DeviceDeviceListOptions ManifestTimestampGreaterThan(DateTime value);
        DeviceDeviceListOptions MechanismEqualTo(DeviceMechanism value);
        DeviceDeviceListOptions MechanismNotEqualTo(DeviceMechanism value);
        DeviceDeviceListOptions MechanismIn(params DeviceMechanism[] value);
        DeviceDeviceListOptions MechanismNotIn(params DeviceMechanism[] value);
        DeviceDeviceListOptions MechanismUrlEqualTo(string value);
        DeviceDeviceListOptions MechanismUrlNotEqualTo(string value);
        DeviceDeviceListOptions MechanismUrlIn(params string[] value);
        DeviceDeviceListOptions MechanismUrlNotIn(params string[] value);
        DeviceDeviceListOptions NameEqualTo(string value);
        DeviceDeviceListOptions NameNotEqualTo(string value);
        DeviceDeviceListOptions NameIn(params string[] value);
        DeviceDeviceListOptions NameNotIn(params string[] value);
        DeviceDeviceListOptions SerialNumberEqualTo(string value);
        DeviceDeviceListOptions SerialNumberNotEqualTo(string value);
        DeviceDeviceListOptions SerialNumberIn(params string[] value);
        DeviceDeviceListOptions SerialNumberNotIn(params string[] value);
        DeviceDeviceListOptions StateEqualTo(DeviceState value);
        DeviceDeviceListOptions StateNotEqualTo(DeviceState value);
        DeviceDeviceListOptions StateIn(params DeviceState[] value);
        DeviceDeviceListOptions StateNotIn(params DeviceState[] value);
        DeviceDeviceListOptions UpdatedAtIn(params DateTime[] value);
        DeviceDeviceListOptions UpdatedAtNotIn(params DateTime[] value);
        DeviceDeviceListOptions UpdatedAtLessThan(DateTime value);
        DeviceDeviceListOptions UpdatedAtGreaterThan(DateTime value);
        DeviceDeviceListOptions VendorIdEqualTo(string value);
        DeviceDeviceListOptions VendorIdNotEqualTo(string value);
        DeviceDeviceListOptions VendorIdIn(params string[] value);
        DeviceDeviceListOptions VendorIdNotIn(params string[] value);
    }
}