/* 
 * <auto-generated>
 * Update Service API
 *
 * This is the API documentation for the Mbed deployment service, which is part of the update service.
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * </auto-generated>
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using update_service.Api;
using update_service.Model;
using update_service.Client;
using System.Reflection;

namespace update_service.Test
{
    /// <summary>
    ///  Class for testing UpdateCampaignPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateCampaignPostRequestTests
    {
        // TODO uncomment below to declare an instance variable for UpdateCampaignPostRequest
        //private UpdateCampaignPostRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateCampaignPostRequest
            //instance = new UpdateCampaignPostRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateCampaignPostRequest
        /// </summary>
        [Test]
        public void UpdateCampaignPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateCampaignPostRequest
            //Assert.IsInstanceOfType<UpdateCampaignPostRequest> (instance, "variable 'instance' is a UpdateCampaignPostRequest");
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'RootManifestId'
        /// </summary>
        [Test]
        public void RootManifestIdTest()
        {
            // TODO unit test for the property 'RootManifestId'
        }
        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }
        /// <summary>
        /// Test the property 'When'
        /// </summary>
        [Test]
        public void WhenTest()
        {
            // TODO unit test for the property 'When'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'DeviceFilter'
        /// </summary>
        [Test]
        public void DeviceFilterTest()
        {
            // TODO unit test for the property 'DeviceFilter'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
