// <auto-generated>
//
// Generated by
//                     _                        _
//   /\/\   __ _ _ __ | |__   __ _ ___ ___  ___| |_
//  /    \ / _` | '_ \| '_ \ / _` / __/ __|/ _ \ __|
// / /\/\ \ (_| | | | | | | | (_| \__ \__ \  __/ |_
// \/    \/\__,_|_| |_|_| |_|\__,_|___/___/\___|\__| v 2.0.0
//
// <copyright file="ITrustedCertificateListOptions.cs" company="Arm">
// Copyright (c) Arm. All rights reserved.
// </copyright>
// </auto-generated>

namespace Mbed.Cloud.Foundation
{
    using Mbed.Cloud.Common;
    using Mbed.Cloud.Common.Filters;
    using Mbed.Cloud.Foundation.Enums;

    /// <summary>
    /// TrustedCertificateListOptions
    /// </summary>
    public interface ITrustedCertificateListOptions : IQueryOptions
    {
        /// <summary>
        /// Filter object
        /// </summary>
        Filter Filter
        {
            get;
            set;
        }

        TrustedCertificateListOptions NameEqualTo(string value);
        TrustedCertificateListOptions ServiceEqualTo(TrustedCertificateService value);
        TrustedCertificateListOptions ExpireEqualTo(string value);
        TrustedCertificateListOptions DeviceExecutionModeEqualTo(int value);
        TrustedCertificateListOptions DeviceExecutionModeNotEqualTo(int value);
        TrustedCertificateListOptions OwnerEqualTo(string value);
        TrustedCertificateListOptions EnrollmentModeEqualTo(bool value);
        TrustedCertificateListOptions StatusEqualTo(TrustedCertificateStatus value);
        TrustedCertificateListOptions IssuerLike(string value);
        TrustedCertificateListOptions SubjectLike(string value);
        TrustedCertificateListOptions ValidEqualTo(bool value);
    }
}