// <auto-generated>
//
// Generated by
//                     _                        _
//   /\/\   __ _ _ __ | |__   __ _ ___ ___  ___| |_
//  /    \ / _` | '_ \| '_ \ / _` / __/ __|/ _ \ __|
// / /\/\ \ (_| | | | | | | | (_| \__ \__ \  __/ |_
// \/    \/\__,_|_| |_|_| |_|\__,_|___/___/\___|\__| v 1.0.0
//
// <copyright file="DeviceEvents.cs" company="Arm">
// Copyright (c) Arm. All rights reserved.
// </copyright>
// </auto-generated>

namespace MbedCloud.SDK.Entities
{
    using MbedCloud.SDK.Common;
    using System.Collections.Generic;
    using System;

    /// <summary>
    /// DeviceEvents
    /// </summary>
    public class DeviceEvents : Entity
    {
        /// <summary>
        /// changes
        /// </summary>
        public Dictionary<string, string> Changes
        {
            get;
            set;
        }

        /// <summary>
        /// created_at
        /// </summary>
        public DateTime? CreatedAt
        {
            get;
            set;
        }

        /// <summary>
        /// data
        /// </summary>
        public Dictionary<string, string> Data
        {
            get;
            set;
        }

        /// <summary>
        /// date_time
        /// </summary>
        public DateTime? DateTime
        {
            get;
            set;
        }

        /// <summary>
        /// description
        /// </summary>
        public string Description
        {
            get;
            set;
        }

        /// <summary>
        /// device_id
        /// </summary>
        public string DeviceId
        {
            get;
            set;
        }

        /// <summary>
        /// event_type
        /// </summary>
        public string EventType
        {
            get;
            set;
        }

        /// <summary>
        /// event_type_category
        /// </summary>
        public string EventTypeCategory
        {
            get;
            set;
        }

        /// <summary>
        /// event_type_description
        /// </summary>
        public string EventTypeDescription
        {
            get;
            set;
        }

        /// <summary>
        /// state_change
        /// </summary>
        public bool? StateChange
        {
            get;
            set;
        }
    }
}