/* 
 * <auto-generated>
 * Device Directory API
 *
 * This is the API Documentation for the Mbed Device Directory service.
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * </auto-generated>
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using device_directory.Api;
using device_directory.Model;
using device_directory.Client;
using System.Reflection;

namespace device_directory.Test
{
    /// <summary>
    ///  Class for testing DeviceData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeviceDataTests
    {
        // TODO uncomment below to declare an instance variable for DeviceData
        //private DeviceData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeviceData
            //instance = new DeviceData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceData
        /// </summary>
        [Test]
        public void DeviceDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeviceData
            //Assert.IsInstanceOfType<DeviceData> (instance, "variable 'instance' is a DeviceData");
        }

        /// <summary>
        /// Test the property 'BootstrapExpirationDate'
        /// </summary>
        [Test]
        public void BootstrapExpirationDateTest()
        {
            // TODO unit test for the property 'BootstrapExpirationDate'
        }
        /// <summary>
        /// Test the property 'BootstrappedTimestamp'
        /// </summary>
        [Test]
        public void BootstrappedTimestampTest()
        {
            // TODO unit test for the property 'BootstrappedTimestamp'
        }
        /// <summary>
        /// Test the property 'ConnectorExpirationDate'
        /// </summary>
        [Test]
        public void ConnectorExpirationDateTest()
        {
            // TODO unit test for the property 'ConnectorExpirationDate'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'CaId'
        /// </summary>
        [Test]
        public void CaIdTest()
        {
            // TODO unit test for the property 'CaId'
        }
        /// <summary>
        /// Test the property 'DeviceClass'
        /// </summary>
        [Test]
        public void DeviceClassTest()
        {
            // TODO unit test for the property 'DeviceClass'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'EndpointName'
        /// </summary>
        [Test]
        public void EndpointNameTest()
        {
            // TODO unit test for the property 'EndpointName'
        }
        /// <summary>
        /// Test the property 'AutoUpdate'
        /// </summary>
        [Test]
        public void AutoUpdateTest()
        {
            // TODO unit test for the property 'AutoUpdate'
        }
        /// <summary>
        /// Test the property 'HostGateway'
        /// </summary>
        [Test]
        public void HostGatewayTest()
        {
            // TODO unit test for the property 'HostGateway'
        }
        /// <summary>
        /// Test the property 'DeviceExecutionMode'
        /// </summary>
        [Test]
        public void DeviceExecutionModeTest()
        {
            // TODO unit test for the property 'DeviceExecutionMode'
        }
        /// <summary>
        /// Test the property 'Mechanism'
        /// </summary>
        [Test]
        public void MechanismTest()
        {
            // TODO unit test for the property 'Mechanism'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Etag'
        /// </summary>
        [Test]
        public void EtagTest()
        {
            // TODO unit test for the property 'Etag'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'FirmwareChecksum'
        /// </summary>
        [Test]
        public void FirmwareChecksumTest()
        {
            // TODO unit test for the property 'FirmwareChecksum'
        }
        /// <summary>
        /// Test the property 'ManifestTimestamp'
        /// </summary>
        [Test]
        public void ManifestTimestampTest()
        {
            // TODO unit test for the property 'ManifestTimestamp'
        }
        /// <summary>
        /// Test the property 'VendorId'
        /// </summary>
        [Test]
        public void VendorIdTest()
        {
            // TODO unit test for the property 'VendorId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DeployedState'
        /// </summary>
        [Test]
        public void DeployedStateTest()
        {
            // TODO unit test for the property 'DeployedState'
        }
        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }
        /// <summary>
        /// Test the property 'EndpointType'
        /// </summary>
        [Test]
        public void EndpointTypeTest()
        {
            // TODO unit test for the property 'EndpointType'
        }
        /// <summary>
        /// Test the property 'Deployment'
        /// </summary>
        [Test]
        public void DeploymentTest()
        {
            // TODO unit test for the property 'Deployment'
        }
        /// <summary>
        /// Test the property 'MechanismUrl'
        /// </summary>
        [Test]
        public void MechanismUrlTest()
        {
            // TODO unit test for the property 'MechanismUrl'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DeviceKey'
        /// </summary>
        [Test]
        public void DeviceKeyTest()
        {
            // TODO unit test for the property 'DeviceKey'
        }
        /// <summary>
        /// Test the property 'EnrolmentListTimestamp'
        /// </summary>
        [Test]
        public void EnrolmentListTimestampTest()
        {
            // TODO unit test for the property 'EnrolmentListTimestamp'
        }
        /// <summary>
        /// Test the property 'Manifest'
        /// </summary>
        [Test]
        public void ManifestTest()
        {
            // TODO unit test for the property 'Manifest'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Test]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
